[env]
TERM ="alacritty"

[window]
padding = { x = 0, y = 0 }
# dynamic_padding = true
decorations = "None"
[colors.primary]
background = "#282a2e"

[font]
size = 12
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font" 

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
    { key = "F", mods = "Control", chars = "tmux-sessionizer\n" },
    { key = "Insert", mods = "Shift", action = "Paste" },
]
