vim.api.nvim_create_user_command("PythonConfig", function()
	local cwd = vim.fn.getcwd()
	vim.fn.system({ "cp", vim.fn.expand("~/.config/nvim/.nvim/pyproject.toml"), cwd })
end, {})

vim.api.nvim_create_user_command("VenvCreate", function()
	vim.fn.system({ "mkdir", "venv" })
	vim.fn.system({ "python3", "-m", "venv", "venv" })
	vim.cmd.PythonConfig()
end, {})
